Hexastack/Hexabot

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md
This PR adds the code of conduct and contribution policy.
=> docs: code of conduct + contributing

frontend/.dockerignore
This PR adds dockerignore config file to the frontend.
=> feat(frontend): add dockerignore

frontend/src/layout/VerticalMenu.tsx
This feature is not ready yet, but present in the sidebar.
=> fix: remove bulk import menu item

api/src/config/index.ts, frontend/src/app-components/logos/HexabotLogo.tsx
Update default storage module to 'disk'
=> fix: attachment upload

frontend/src/components/contents/ContentDialog.tsx, frontend/src/components/visual-editor/form/ListMessageForm.tsx, frontend/src/types/content-type.types.ts
Remove unecessary field type from the content type.
=> fix: remove unecessary field type

CONTRIBUTING.md, README.md, SECURITY.md, api/README.md, frontend/README.md, nlu/README.md, widget/README.md
=> fix: update discord link

frontend/src/components/nlp/components/NlpSample.tsx, frontend/src/utils/URL.ts
=> [ISSUE] #19 Fix urls (trailing or missing slashes)

frontend/src/components/profile/profile.tsx, frontend/src/hooks/entities/auth-hooks.ts, frontend/src/hooks/useAuth.tsx
Logs out (react query state update) the user before refreshing the page.
Fixes #35
=> fix: logout page reload

.github/workflows/docker.yml, docker/docker-compose.nlu.yml, docker/docker-compose.yml
Fixes wrong naming for docker images.
=> fix: docker images in compose file

widget/README.md
remove extra spaces in the widget README file.
=> fix(widget): remove extra spaces in README

docker/docker-compose.dev.yml
Fixes Dev compose file : duplicate service
=> fix: dev compose file

docker/docker-compose.dev.yml
Force building docker images when running "make dev"
=> fix: docker compose force build in dev env

frontend/src/app-components/auth/Register.tsx, frontend/src/i18n/en/translation.json
Enhances the signup completion message to increase clarity.
Fixes #44 
=> fix: enhance signup completion message clarity

frontend/src/components/labels/index.tsx, frontend/src/components/subscribers/index.tsx
This PR solves the issue mentioned in #43 raised by @Emnaghz 
Fixes #43 
=> Resolved Issue #43 - Update Icons for Labels and Subscribers

frontend/src/i18n/fr/translation.json
Uppercase the first letter in NLP Value dialog form fields.
Fixes #31
=> fix: nlp value uppercase fr translation first letter

frontend/src/components/subscribers/index.tsx, frontend/src/i18n/en/translation.json, frontend/src/i18n/fr/translation.json
currently in the subscriber module if the labels list is empty then an empty dropdown is shown that looks bad and is not a good UI experience.
in this fix i have added a default item which will be show in case the labels list is empty
Fixes #61 
after the fix the label dropdown contains a defalut disabled menuItem if the list is empty
=> #61 Added default item in case of empty list in labels dropdown in subscriber section

nlu/requirements.txt
=> fix: NLU image's building error

.github/workflows/docker.yml
=> fix: add target on widget build job

api/src/main.ts, package-lock.json
=> fix: api validation pipe

frontend/src/hooks/usePagination.ts
Increased page size to change the default list row count to 10.
Fixes  https://github.com/Hexastack/Hexabot/issues/82
=> fix: increased the default number of pagesize

api/src/i18n/services/translation.service.spec.ts
added unit tests to the API's TranslationService : api/src/i18n/services/translation.service.ts
Fixes # (issue) #87 
=> feat: add unit tests to the api translation service

frontend/src/components/visual-editor/hooks/useVisualEditor.tsx, frontend/src/components/visual-editor/v2/AdvancedLink/AdvancedLink.tsx, frontend/src/components/visual-editor/v2/AdvancedLink/AdvancedLinkFactory.tsx, frontend/src/components/visual-editor/v2/AdvancedLink/AdvancedLinkModel.tsx, frontend/src/components/visual-editor/v2/Diagrams.tsx
=> Feat: Self Attached Node

frontend/package.json, package-lock.json
The motivation of this PR is to fix the **SSRF vulnerability** embedded in the **axios** package used by the Frontend App
Fixes https://github.com/Hexastack/Hexabot/issues/107
=> fix(frontend): axios SSRF vulnerability

api/package-lock.json, api/package.json, api/test/setup-tests.ts
The following fixes some issues with node dependencies in the API for MacOs users (M1/M2 chips).
=> fix: api docker container for mac users

docker/docker-compose.yml
=> fix: add port to widget service on docker-compose

api/src/chat/repositories/label.repository.ts, api/src/chat/repositories/subscriber.repository.ts, api/src/chat/schemas/subscriber.schema.ts, api/src/chat/schemas/types/subscriberContext.ts, api/src/chat/services/block.service.ts, api/src/chat/services/chat.service.ts, api/src/cms/schemas/types/menu.ts
Apply consistent naming of events in the API.
=> fix: event consistent naming

frontend/src/hooks/useToast.ts
=> fix: lint errors

README.md, cli/src/index.ts
We need to make sure that renaming the plugin does handle all sort of extensions.
=> fix: cli prefix sanitize

cli/src/index.ts
=> fix: missing cli init cmd

README.md
Add logo + badges to the README file.
=> Feat/readme badges + logo

frontend/Dockerfile
The following PR fixes the frontend Dockerfile for production. There's was a path issue caused by the mono-repo setup.
=> fix: frontend Dockerfile for production

frontend/src/hooks/useAuth.ts
The main motivation is to fix the missed dynamic id in the next param after the automatic logout of a user.  
Fixes #139
=> fix(frontend): logout redirection logic

api/src/cms/controllers/content.controller.ts
The motivation is to remove the unused filterDynamicFields method from the ContentController class.
Fixes #141
=> fix(api): remove unused filterDynamicFields method

frontend/src/components/visual-editor/form/TextMessageForm.tsx, frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx, frontend/src/components/visual-editor/form/utils/inputControls.ts
The main motivation is fix visual editor blocks types.
Fixes #147
=> fix(frontend): instable blocks type

README.md
Add video in the README file + link to the Youtube video tutorial.
=> feat: add README video

README.md
=> Update Video README.md

README.md
=> Update README.md (FINAL)

frontend/src/components/nlp/components/NlpTrainForm.tsx, frontend/src/hooks/useTranslate.tsx, frontend/src/i18n/i18n.types.ts
=> fix(frontend): NLU Training I18n translation issue

frontend/src/components/content-types/EditContentTypeFieldsDialog.tsx
The main motivation is to fix the cache issue in the UI of the content type page.
Fixes #169
=> fix(frontend): content type update cache issue

frontend/src/app-components/widget/ChatWidget.tsx, frontend/src/app-components/widget/ChatWidgetHeader.tsx, frontend/src/layout/Header.tsx, frontend/src/layout/index.tsx, frontend/src/pages/visual-editor.tsx
The main motivation is  to move the widget to the header to resolve the websocket issues
Fixes #171
=> fix(frontend):  Websocket connections issue

api/src/nlp/services/nlp.service.ts
The PR fixes an issue where once the app is started, the NLU helper does not get instanciated, thus, any NLU inference will not work unless you update the NLU settings.
=> fix: nlu helper init

api/src/analytics/services/bot-stats.service.ts, api/src/chat/services/subscriber.service.ts, api/src/eventemitter.d.ts, api/src/extensions/channels/offline/index.channel.ts, api/src/i18n/repositories/language.repository.ts, api/src/nlp/lib/BaseNlpHelper.ts, api/src/nlp/repositories/nlp-entity.repository.ts, api/src/nlp/repositories/nlp-value.repository.ts, api/src/nlp/services/nlp.service.ts, api/src/setting/repositories/setting.repository.ts, api/src/setting/services/setting.service.ts, api/src/utils/generics/base-repository.ts
The main motivation is enhancing events typing 
Fixes #165
=> 165 issue untyped events and event listeners

api/src/nlp/controllers/nlp-sample.controller.spec.ts, api/src/nlp/controllers/nlp-sample.controller.ts, frontend/src/components/nlp/components/NlpSample.tsx
This PR includes the ability to delete multiple nlu samples at once.
Fixes [# (issue)](https://github.com/Hexastack/Hexabot/issues/178)
=> feat: NLP samples bulk delete

widget/src/components/UserSubscription.scss
The main motivation is to add a scrollbar to the widget.
Before the update:
After the update:
=> fix(widget): add scrollbar

api/src/nlp/controllers/nlp-entity.controller.spec.ts, api/src/nlp/controllers/nlp-entity.controller.ts, frontend/src/components/nlp/components/NlpEntity.tsx
This PR includes the implementation of bulk delete functionality via check-boxes, and upon clicking "Delete," the selected entities should be removed from the list after confirmation.
Fixes [# (issue)](https://github.com/Hexastack/Hexabot/issues/189)
=> feat: [NLP Entity] add bulk delete

api/src/nlp/controllers/nlp-value.controller.spec.ts, api/src/nlp/controllers/nlp-value.controller.ts, frontend/src/components/nlp/components/NlpSample.tsx, frontend/src/components/nlp/components/NlpValues.tsx
This PR includes the implementation of bulk delete functionality via check-boxes, and upon clicking "Delete," the selected values should be removed from the list after confirmation.
Fixes [# (issue)](https://github.com/Hexastack/Hexabot/issues/190)
=> feat: [NLP Value] add bulk delete

api/src/nlp/schemas/nlp-sample.schema.ts
The main motivation is to fix the lost of chat messages.
Fixes #184
=> fix(api): nlp-sample schema remove unique from text field

api/package.json, api/src/channel/channel.service.ts, api/src/websocket/websocket.gateway.spec.ts, api/src/websocket/websocket.gateway.ts, frontend/src/app-components/widget/ChatWidget.tsx, frontend/src/hooks/entities/auth-hooks.ts
The motivation is to enhance web-socket connection access.
Fixes #196
=> fix: enhance web-socket connection access

widget/src/components/Messages.tsx
The main motivation is to fix the widget scrollbar freeze.
Fixes #202
=> fix(widget): scrollbar freeze

frontend/src/components/visual-editor/v2/Diagrams.tsx
The motivation is to fix attachment port link issue. 
Fixes #207
=> fix(frontend): attachment port link issue

api/src/chat/services/conversation.service.ts, api/src/chat/services/label.service.ts, api/src/chat/services/message.service.ts, api/src/chat/services/subscriber.service.ts, api/src/utils/generics/base-service.ts
The motivation of this update is to refactor the base service file and simplify duplicated logic.
Fixes #204
=> refactor(api): simplify services logic

api/migrations/models/index.ts, api/src/attachment/controllers/attachment.controller.ts, frontend/src/components/contents/ContentImportDialog.tsx, frontend/src/components/nlp/NlpImportDialog.tsx, frontend/src/components/visual-editor/form/MessageForm.tsx, frontend/src/services/api.class.ts, frontend/src/types/message.types.ts
The main motivation of this update is to fix an inconsistency in the naming conventions used for attachment cross the project.
Fixes #209
=> fix: attachment spelling issue

frontend/src/app-components/auth/Login.tsx, frontend/src/app-components/auth/Register.tsx, frontend/src/app-components/auth/ResetPassword.tsx, frontend/src/app-components/auth/resetPasswordRequest.tsx, frontend/src/components/anonymous/PublicContentWrapper.tsx
The main motivation of this update is to fix public pages extra rendering.
Before the update :
<video src ="https://github.com/user-attachments/assets/2c884743-a29a-4e30-b035-17b2ab6c2e2f" />
After the update :
<video src="https://github.com/user-attachments/assets/27dac394-eb0b-404d-a838-c33bdc6ad432" />
Fixes #215
=> fix(frontend): public pages extra rendering

api/src/eventemitter.d.ts, api/src/setting/repositories/setting.repository.ts
The main motivation is to fix settings types
Fixes #227
=> fix(api): settings types

.github/pull_request_template.md
The main motivation is to enhance GitHub PR template.
Fixes #231
=> fix: github PR template

frontend/src/contexts/config.context.tsx
Enforce typing in the config context provider.
=> fix(frontend): config context typing

frontend/.eslintrc.json, frontend/src/components/categories/index.tsx, frontend/src/components/inbox/components/Chat.tsx, frontend/src/components/inbox/hooks/useInfiniteLiveMessages.ts, frontend/src/components/visual-editor/BlockDialog.tsx, frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx, frontend/src/components/visual-editor/v2/Diagrams.tsx, frontend/src/hooks/crud/useCreate.tsx, frontend/src/hooks/crud/useDelete.tsx, frontend/src/hooks/crud/useDeleteMany.tsx, frontend/src/hooks/crud/useFind.tsx, frontend/src/hooks/crud/useGet.tsx, frontend/src/hooks/crud/useInfiniteFind.ts, frontend/src/hooks/crud/useNormalizedInfiniteQuery.ts, frontend/src/hooks/crud/useUpdate.tsx, frontend/src/hooks/crud/useUpload.tsx
The motivation is to order well Frontend imports.
Fixes #236
=> fix(frontend): eslint imports order

api/src/chat/services/chat.service.ts, api/src/eventemitter.d.ts
The main motivation is to make stronger the event typing.
Fixes #245
=> fix(api): enhance event typing

api/src/chat/schemas/message.schema.ts, api/src/nlp/services/nlp-sample.service.ts
=> fix: ts issue (event listener)

frontend/src/app-components/logos/HexabotLogoRound.tsx, frontend/src/app-components/widget/ChatWidgetHeader.tsx, widget/src/components/ChatHeader.scss, widget/src/components/ChatHeader.tsx, widget/src/providers/SettingsProvider.tsx
Defines the Hexabot logo in the Chat widget window header.
=> feat: hexabot logo in the widget header

api/src/eventemitter.d.ts, api/src/utils/generics/base-repository.ts
The main motivation is to resolve the base-repository.ts file typing errors.
Fixes #268
=> fix(api): enhance base-repository.ts typing

docker/docker-compose.nlu.yml
Add NLU data volume to avoid downloading models when container is started.
=> fix: add nlu data volume

api/package-lock.json
=> fix: pkg lock version

README.md
The motivation of this PR is to update README.md file
=> fix: update README.md file

frontend/src/app-components/inputs/AutoCompleteSelect.tsx
The main motivation of this PR is to fix unchanged language field in the NLU page.
Fixes #162
<video src="https://github.com/user-attachments/assets/a11ebaa3-e4c3-4e6b-bba4-cf49a3f68dba" />
=> fix(frontend): unchanged language+logic enhancement

api/src/chat/chat.module.ts
The main motivation of this PR is to export conversation service from chat.module 
HOTFIX
=> fix(api): chat.module.ts export conversationService

api/package-lock.json, api/package.json
=> build: bump api version

package-lock.json, widget/package.json
=> build: bump widget version

api/.dockerignore
The main motivation of this PR is to enhance .dockerignore file of the api.
Fixes #291
=> fix(api): enhance .dockerigonre file

api/src/chat/services/conversation.service.ts
The main motivation of this PR is to fix the persistence contextVars bug.
Fixes #296
=> fix(api): persistence contextVars

api/package-lock.json, api/package.json
=> build: bump version

frontend/src/types/language.types.ts
The motivation of this PR is to fix the ILanguageStub issue.
Fixes #304
=> fix(frontend): ILanguageStub typing

api/src/global.d.ts, api/tsconfig.json, api/types/event-emitter.d.ts, api/types/express-session.d.ts
The main motivation is to centralize type in one place.
Fixes #301
=> fix(api): move types to global.d.ts

frontend/src/app-components/attachment/AttachmentUploader.tsx, frontend/src/app-components/attachment/MultipleAttachmentInput.tsx, frontend/src/components/settings/SettingInput.tsx
This PR includes the implementation of multiple attachment input
=> feat: add multiple attachment input

api/tsconfig.json
The main motivation is to fix a tsconfig hotfix 
HOTFIX
=> fix: tsconfig to support modules

api/package-lock.json, api/package.json
=> build: version v2.0.10 bump

api/src/app.controller.ts
The main motivation is to 
Fixes #318
=> fix: remove unused endpoints

api/package-lock.json, api/package.json, package-lock.json, widget/package.json
- Bump versions : API + widget
=> build: bum versions

frontend/src/components/visual-editor/index.tsx
The main motivation of this PR is to fix the Visual Editor scrollbar issue.
Fixes #327 
<video src="https://github.com/user-attachments/assets/c6fba5dd-56c6-4abf-8080-c3f49802cc00" />
=> fix: visual editor scrollbar issue

api/src/plugins/plugins.module.ts
Add HTTP module import for the plugins to allow them to send requests to 3rd party APIs for example.
=> feat: add http module for plugins

docker/docker-compose.nginx.yml, docker/nginx/secure/default.conf.template, docker/nginx/unsecure/default.conf.template
In this PR we removed widget dependency from nginx
Fixes #(219) [BUG] - Enabling Nginx doesn't work.
=> removed  widget dependency from nginx

docker/docker-compose.yml
This PR includes a fix for the path for mounting the api service volume.
Fixes [# (issue)](https://github.com/Hexastack/Hexabot/issues/348)
=> fix: api service volume

api/src/nlp/controllers/nlp-sample.controller.ts
Fixes the call to NLP format function by awaiting for the promise.
=> fix: add missing await for NLP format

docker/.env.example, nlu/main.py
Implement login functionality for HuggingFace using an access token from environment variables.
=> Add HuggingFace login functionality

api/src/chat/controllers/block.controller.ts, frontend/src/app-components/dialogs/DeleteDialog.tsx, frontend/src/components/visual-editor/v2/Diagrams.tsx
This PR includes a fix for blocks bulk removal in the visual editor.
Fixes [# (issue)](https://github.com/Hexastack/Hexabot/issues/266)
=> fix: incomplete blocks removal during delete operation

api/src/channel/lib/Handler.ts
In this PR, we remove some methods that are not required for any channel. It's up to the developer to decide how to implement and/or name them.
=> fix: remove unecessary channel handler methods

api/types/event-emitter.d.ts
This PR adds a new analytics event.
=> feat: add analytics intervention event

api/package-lock.json, api/package.json
=> build: bump v2.0.15

api/src/chat/schemas/conversation.schema.ts
Add missing lifecycle hooks to the conversation repository.
=> fix: add missing lifecycle hooks to the conversation

api/package-lock.json, api/package.json
=> build: version bump v2.0.16

api/src/chat/services/chat.service.ts
Apply NLP threshold on prediction to force global fallback when there is no matching blocks.
=> fix: apply nlp threshold

api/package-lock.json, api/package.json
=> build: bump version 2.0.17

nlu/data_loaders/jisfdl.py, nlu/models/slot_filler.py
=> fix: fix inference, retrieve synonym map & fix slot names

package-lock.json
This PR updates the package-lock.json file to include the latest changes, which were inadvertently omitted in a previous update related to fixing the ESLint configuration for the widget. This resolves pipeline issues caused by the missing updates.
Fixes #322
=> fix: package lock json

api/src/attachment/controllers/attachment.controller.ts, api/src/cms/controllers/menu.controller.ts, api/src/cms/repositories/content.repository.ts, api/src/cms/services/content.service.ts, api/src/extensions/helpers/core-nlu/index.helper.ts, api/src/i18n/controllers/translation.controller.ts, api/src/nlp/services/nlp-sample-entity.service.ts, api/src/user/controllers/user.controller.ts, api/src/user/services/passwordReset.service.ts, api/src/user/services/validate-account.service.ts, frontend/src/websocket/SocketIoClient.ts, widget/src/utils/SocketIoClient.ts
The main motivation of this PR is to add missing await cross Hexabot app's.
=> fix: add missing await

api/src/channel/lib/EventWrapper.ts, api/src/channel/lib/Handler.ts, api/src/chat/controllers/message.controller.ts, api/src/chat/dto/subscriber.dto.ts, api/src/chat/index.d.ts, api/src/chat/schemas/subscriber.schema.ts, api/src/chat/schemas/types/channel.ts, api/src/chat/services/block.service.spec.ts, api/src/chat/services/bot.service.spec.ts, api/src/chat/services/chat.service.ts, api/src/chat/services/conversation.service.ts, api/src/extensions/channels/console/index.d.ts, api/src/extensions/channels/web/__test__/wrapper.spec.ts, api/src/extensions/channels/web/base-web-channel.ts, api/src/extensions/channels/web/index.d.ts, api/src/extensions/channels/web/types.ts, api/src/extensions/channels/web/wrapper.ts
=> fix: channels data type inference

frontend/public/locales/en/translation.json, frontend/public/locales/fr/translation.json, frontend/src/app-components/buttons/DropdownButton.tsx, frontend/src/app-components/inputs/MultipleInput.tsx, frontend/src/components/visual-editor/form/inputs/message/ButtonInput.tsx, frontend/src/components/visual-editor/form/inputs/message/ButtonsInput.tsx, frontend/src/components/visual-editor/form/inputs/message/QuickRepliesInput.tsx, frontend/src/components/visual-editor/form/inputs/message/QuickReplyInput.tsx
This PR includes some minor enhancements on repeatable fieldsets. 
Fixes [# (issue)](https://github.com/Hexastack/Hexabot/issues/423)
=> feat: ux enhancement on repeatable fieldsets

api/src/attachment/services/attachment.service.ts
The motivation of this PR is to refactor attachment service uploadfiles method
Fixes #430
=> refactor: attachment service uploadFiles method

api/src/chat/services/bot.service.ts
=> chore: update bot.service.ts

frontend/src/app-components/inputs/ToggleableInput.tsx, frontend/src/components/visual-editor/form/ListMessageForm.tsx, frontend/src/components/visual-editor/form/inputs/message/ButtonInput.tsx, frontend/src/components/visual-editor/form/inputs/message/ButtonsInput.tsx
This PR fixes the buttons form display within the list/carousel form so that it would take the full width :
=> fix: Buttons display in the list/carousel block form

frontend/src/components/visual-editor/v2/Diagrams.tsx
This PR main motivation is to fix visual editor navigation bug.
<video src="https://github.com/user-attachments/assets/fd360459-e552-44f8-99eb-fe236b04f288"></video>
Fixes #454
=> fix(frontend): handle visual editor default flow navigation

api/types/event-emitter.d.ts
The main motivation of this PR is to add select all selector to the custom events
Fixes #455
=> fix(api): add select all selector to the custom events

api/src/chat/services/chat.service.ts
Removes unecessary WS broadcast call.
=> fix: remove unecessary ws broadcast

api/src/channel/lib/EventWrapper.ts, api/src/chat/services/conversation.service.ts
Type the return value of getMessage() in the event wrapper.
=> fix: type getMessage()

api/src/setting/repositories/setting.repository.spec.ts, api/src/setting/repositories/setting.repository.ts
In this PR we fix missing event emit in the settings repository. 
Added unit tests as well to make it rock solid.
=> fix: setting emit + unit tests

api/src/utils/generics/base-repository.ts, api/src/utils/generics/base-service.ts, api/src/utils/generics/lifecycle-hook-manager.ts, api/src/utils/pagination/pagination-query.dto.ts
This PR updates base-repository typing to work correctly in strictNullChecks mode.
Fixes #443 
=> Fix: base repository with strict null checks

api/src/seeder.ts, api/src/setting/controllers/setting.controller.spec.ts, api/src/setting/repositories/setting.repository.ts, api/src/setting/schemas/types.ts, api/src/setting/services/setting.service.spec.ts, api/src/utils/generics/base-repository.ts, api/src/utils/pagination/pagination-query.dto.ts
This PR makes the settings compliant with strictNullChecks tsconfng
This PR should be merged after base-repository #467
=> fix: settings strict null checks

api/src/utils/constants/session-store.ts, api/src/websocket/services/socket-event-dispatcher.service.ts, api/src/websocket/utils/gateway-options.ts, api/src/websocket/websocket.gateway.spec.ts
=> fix: socketio types

api/src/config/index.ts, api/src/i18n/controllers/language.controller.spec.ts, api/src/i18n/controllers/translation.controller.spec.ts, api/src/i18n/i18n.module.ts, api/src/i18n/services/i18n.service.ts, api/src/i18n/services/language.service.ts, api/src/i18n/services/translation.service.ts, api/src/user/controllers/auth.controller.spec.ts, api/src/user/controllers/user.controller.spec.ts, api/src/user/services/invitation.service.spec.ts, api/src/user/services/passwordReset.service.spec.ts, api/src/user/services/validate-account.service.spec.ts, api/src/utils/test/fixtures/language.ts
=> Fix: i18n and translation strict null check

api/src/analytics/schemas/bot-stats.schema.ts
This PR makes bot-stats comply with ts-strict-null-check
=> fix: bot stats to comply with strict null check

package-lock.json
The main motivation of this PR is to fix an issue happening in the build step.
Fixes #505
=> fix: update package-lock.json file

api/src/websocket/adapters/redis-io.adapter.ts
=> fix: socketio redis adapter

api/src/user/controllers/permission.controller.spec.ts, api/src/user/controllers/permission.controller.ts, api/src/user/controllers/role.controller.spec.ts, api/src/user/repositories/permission.repository.spec.ts, api/src/user/repositories/role.repository.spec.ts, api/src/user/services/permission.service.spec.ts, api/src/user/services/role.service.spec.ts
This PR fixes permission & role to comply with strict null check
=> Fix: permission and role ts strict null check

api/src/chat/controllers/category.contoller.spec.ts, api/src/chat/repositories/category.repository.ts
This PR makes category comply with strict null check
=> fix: category

api/src/utils/generics/base-controller.ts
This PR fixes BaseController to comply with strict null check
=> fix: base-controller

frontend/src/hooks/crud/useCreate.tsx, frontend/src/hooks/crud/useDelete.tsx, frontend/src/hooks/crud/useDeleteMany.tsx, frontend/src/hooks/crud/useUpdate.tsx, frontend/src/hooks/crud/useUpdateMany.tsx, frontend/src/hooks/crud/useUpload.tsx
The main motivation of this update is to remove duplicated types
Fixes #518
=> fix(frontend): remove duplicated type declarations

api/src/utils/pipes/search-filter.pipe.ts, api/src/utils/types/filter.types.ts
The motivation of this PR is to resolve search-filterpipe null checks issues
Fixes #529
=> [MERGE ORDER 2] fix: resolve search filterpipe null checks issues

api/src/channel/lib/__test__/common.mock.ts, api/src/chat/schemas/types/attachment.ts, api/src/chat/schemas/types/message.ts, api/src/chat/services/block.service.ts, api/src/cms/services/content.service.ts, api/src/extensions/channels/web/base-web-channel.ts, frontend/src/components/inbox/components/AttachmentViewer.tsx, frontend/src/types/message.types.ts
Remove unecessary typing "WithUrl". Attachment has already "url?" which is a virtual attribute.
=> fix: remove unecessary WithUrl typing

api/src/chat/repositories/subscriber.repository.ts
=> fix: missing value assignedAt

api/src/analytics/services/bot-stats.service.ts
=> fix: event returning users missing required payload

frontend/src/components/media-library/index.tsx
User shouldn't be able to delete attachments from media library 
Temporary mesure for https://github.com/Hexastack/Hexabot/issues/586
=> fix: remove delete opearation

api/src/channel/lib/Handler.ts, api/src/chat/repositories/subscriber.repository.ts, api/src/chat/schemas/types/attachment.ts
Fix minor TS issue  subscriber preupdate hook and keep old typing.
=> fix: Minor ts issue in subscriber preupdate hook

api/nest-cli.json, api/patches/@nestjs-modules+mailer+1.11.2.patch, api/src/app.module.ts, api/src/templates/account_confirmation.mjml, api/src/templates/invitation.mjml, api/src/templates/password_reset.mjml
In this PR:
Test both with smpt4dev and mailtrap: https://docs.hexabot.ai/developer-guide/smtp-configuration-and-emails
- Invitation email
- Password reset request email
- Password reset confirm email
=> fix: nest mailing + minor css tweaks

api/src/user/controllers/auth.controller.ts, api/src/websocket/websocket.gateway.ts, api/types/event-emitter.d.ts
Currently if we logout after opening many only one tab will disconnect. This PR main motivation is to resolve the mentioned bug 
Fixes #644
<video src="https://github.com/user-attachments/assets/db51d46b-a755-4230-a17e-47ebae88fa45"></video>
=> fix: logout disconnection sockets

frontend/src/components/visual-editor/v2/AdvancedLink/AdvancedLinkFactory.tsx, frontend/src/components/visual-editor/v2/BackgroundLayerWidget.tsx, frontend/src/components/visual-editor/v2/CustomCanvasWidget.tsx, frontend/src/components/visual-editor/v2/CustomDiagramNodes/NodeWidget.tsx, frontend/src/styles/visual-editor.css, widget/src/UiChatWidget.css
In this PR we:
- Fixed the visual editor background pattern
- Reduced borders
- Enhanced port in/out spacing
- Minor css fixes
=> feat: enhance visual editor UI

api/package-lock.json, api/package.json, api/src/chat/schemas/types/attachment.ts
This PR adds zod for validation for chat module specifically attachments & infer the types based on the zod schema
=> feat: zod attachment

api/src/chat/schemas/types/capture-var.ts
This PR adds zod for validation for chat module specifically capture-var & infer the types based on the zod schema
=> Feat: zod capture var

api/src/chat/schemas/types/quick-reply.ts
This PR adds zod for validation for chat module specifically `quick-reply` & infer the types based on the zod schema
=> Feat: zod quick reply

api/src/chat/schemas/types/pattern.ts
This PR adds zod for validation for chat module specifically `pattern` & infer the types based on the zod schema
=> Feat: zod pattern

api/src/chat/validation-rules/is-position.ts
This PR replaces joi with zod for `is-position`
=> feat: replace joi with zod is-position

api/src/chat/schemas/types/capture-var.ts, api/src/chat/validation-rules/is-valid-capture.ts, api/src/utils/test/mocks/block.ts
This PR replaces joi with zod for `capture-var`
=> Feat: replace capture var to use zod

api/src/chat/schemas/types/channel.ts, api/src/chat/validation-rules/is-channel-data.ts
This PR adds schema validation for channel with `zod`
=> Feat: add channel schema zod validation

api/src/chat/schemas/types/button.ts
This PR creates zod schema for buttons & infer the typing based on the schema
=> Feat: button schema validation zod

api/src/chat/repositories/subscriber.repository.spec.ts, api/src/chat/repositories/subscriber.repository.ts
Even if the subscriber updates do not include "assignedTo" attribute, the check "undefined !== null" would resolve to true and trigger events.
=> fix: handover/handback lifecycle hook

api/src/extensions/channels/web/base-web-channel.ts
In this PR, we handle multipart file upload in the middleware.
=> fix: handle multer upload in middleware (long pooling only)

frontend/src/app-components/dialogs/GenericFormDialog.tsx, frontend/src/app-components/dialogs/index.ts, frontend/src/components/categories/CategoryFormDialog.tsx, frontend/src/components/context-vars/ContextVarFormDialog.tsx, frontend/src/components/labels/LabelFormDialog.tsx, frontend/src/components/translations/TranslationFormDialog.tsx
The main motivation of this PR is to implement the GenericFormDialog component.
Fixes #692
=> refactor(frontend): implement GenericFormDialog component

frontend/src/app-components/attachment/AttachmentForm.tsx, frontend/src/app-components/dialogs/FormDialog.tsx, frontend/src/components/Menu/MenuForm.tsx, frontend/src/components/categories/CategoryForm.tsx, frontend/src/components/content-types/ContentTypeForm.tsx, frontend/src/components/contents/ContentForm.tsx, frontend/src/components/contents/ContentImportForm.tsx, frontend/src/components/context-vars/ContextVarForm.tsx, frontend/src/components/inbox/components/AttachmentViewerForm.tsx, frontend/src/components/labels/LabelForm.tsx, frontend/src/components/languages/LanguageForm.tsx, frontend/src/components/nlp/components/NlpEntityForm.tsx, frontend/src/components/nlp/components/NlpSampleForm.tsx, frontend/src/components/nlp/components/NlpValueForm.tsx, frontend/src/components/roles/PermissionsBody.tsx, frontend/src/components/roles/RoleForm.tsx, frontend/src/components/subscribers/SubscriberForm.tsx, frontend/src/components/translations/TranslationForm.tsx, frontend/src/components/users/EditUserForm.tsx, frontend/src/components/users/InviteUserForm.tsx, frontend/src/components/visual-editor/BlockEditForm.tsx, frontend/src/components/visual-editor/BlockMoveForm.tsx, frontend/src/types/common/dialogs.types.ts
The main motivation of this PR is to optimize and remove unused code.
Fixes #728
=> refactor(frontend): optimize useDialogs logic

api/src/chat/schemas/types/pattern.ts, api/src/chat/services/block.service.ts
The main motivation is to fix a missing block pattern validations
For more details you can see the dedicated issue https://github.com/Hexastack/Hexabot/issues/765.
Fixes #765
=> fix(api): update string and regex string zod validations

frontend/src/components/inbox/components/ConversationsList.tsx, frontend/src/pages/inbox/index.tsx, frontend/src/pages/inbox/subscribers/[subscriber]/index.tsx, frontend/src/pages/inbox/subscribers/index.tsx
The main motivation of this PR is to fix the issue of refresh the inbox page after selecting a subscriber.
For more details you can see the dedicated issue #760.
Fixes #760
<video src="https://github.com/user-attachments/assets/e862d2cf-ad67-4757-9901-06ed41b48f44"></video>
=> fix(frontend): synchronize selected inbox subscriber with url query

frontend/src/app-components/inputs/Selectable.tsx, frontend/src/components/nlp/components/NlpTrainForm.tsx, frontend/src/pages/inbox/index.tsx, frontend/src/pages/inbox/subscribers/[subscriber]/index.tsx, frontend/src/pages/inbox/subscribers/index.tsx
The main motivation is to remove inbox empty begin lines.
Fixes #778
=> fix(frontend): remove empty blank begin lines from the inbox pages

frontend/src/app-components/inputs/AutoCompleteEntitySelect.tsx, frontend/src/app-components/inputs/Selectable.tsx, frontend/src/components/nlp/components/NlpTrainForm.tsx, frontend/src/pages/inbox/index.tsx, frontend/src/pages/inbox/subscribers/[subscriber]/index.tsx, frontend/src/pages/inbox/subscribers/index.tsx
=> fix: edit nlp sample edit language

frontend/src/app-components/attachment/AttachmentUploader.tsx, frontend/src/app-components/auth/Login.tsx, frontend/src/app-components/auth/Register.tsx, frontend/src/app-components/inputs/Selectable.tsx, frontend/src/components/context-vars/ContextVarForm.tsx, frontend/src/components/inbox/components/Chat.tsx, frontend/src/components/languages/index.tsx, frontend/src/components/nlp/components/NlpSample.tsx, frontend/src/components/nlp/components/NlpTrainForm.tsx, frontend/src/components/nlp/index.tsx, frontend/src/components/profile/profile.tsx, frontend/src/components/settings/index.tsx, frontend/src/components/visual-editor/BlockEditForm.tsx, frontend/src/components/visual-editor/hooks/useVisualEditor.tsx, frontend/src/pages/inbox/index.tsx, frontend/src/pages/inbox/subscribers/[subscriber]/index.tsx, frontend/src/pages/inbox/subscribers/index.tsx, frontend/src/types/visual-editor.types.ts
This pull request refactors the codebase by replacing instances of mutateAsync with mutate
=> feat: replace mutateasync with mutate

api/src/chat/controllers/label.controller.spec.ts, api/src/chat/controllers/label.controller.ts, api/src/chat/repositories/label.repository.ts, api/src/chat/services/block.service.ts, api/src/chat/services/subscriber.service.ts, api/src/utils/test/fixtures/label.ts, frontend/src/components/labels/index.tsx
NB: This PR is a continuation of a previous [PR #703](https://github.com/Hexastack/Hexabot/pull/703)
The main motivation of this PR is to add bulk delete feature for labels
Fixes #701
Checklist:
=> fix: add label bulk delete

api/src/chat/controllers/block.controller.spec.ts, api/src/chat/controllers/label.controller.spec.ts, api/src/chat/controllers/message.controller.spec.ts, api/src/chat/controllers/subscriber.controller.spec.ts, api/src/chat/services/message.service.spec.ts, api/src/chat/services/subscriber.service.spec.ts, api/src/user/controllers/model.controller.spec.ts, api/src/user/controllers/permission.controller.spec.ts, api/src/user/controllers/role.controller.spec.ts, api/src/user/repositories/permission.repository.spec.ts, api/src/user/repositories/role.repository.spec.ts, api/src/user/repositories/role.repository.ts, api/src/user/repositories/user.repository.spec.ts, api/src/user/services/auth.service.spec.ts, api/src/user/services/passwordReset.service.spec.ts, api/src/user/services/permission.service.spec.ts, api/src/user/services/role.service.spec.ts, api/src/user/services/user.service.spec.ts, api/src/user/services/validate-account.service.spec.ts
This PR ensures that when a role is deleted, any invitation that is associated with that role is also removed.
Fixes #780
=> feat: delete invitation on role delete

api/src/chat/controllers/block.controller.ts, api/src/chat/controllers/category.controller.ts, api/src/chat/controllers/context-var.controller.ts, api/src/chat/controllers/label.controller.ts, api/src/nlp/controllers/nlp-entity.controller.ts, api/src/nlp/controllers/nlp-sample.controller.ts, api/src/nlp/controllers/nlp-value.controller.ts
The main motivation is to align deleteMany body ids type with value 
Fixes #801
=> fix(api): align deleteMany ids type with value

api/src/chat/repositories/subscriber.repository.spec.ts, api/src/utils/generics/base-repository.ts, api/types/event-emitter.d.ts
The main motivation is to support emitAsync to enforce a specific execution order in the logic.
Fixes #830
=> feat: add emitAsync support

api/package-lock.json, api/package.json, api/src/app.module.ts, api/src/templates/account_confirmation.mjml, api/src/templates/invitation.mjml, api/src/templates/password_reset.mjml, api/src/user/services/invitation.service.ts, api/src/user/services/passwordReset.service.ts, api/src/user/services/validate-account.service.ts
In this PR we use handlebars as template engine for email templates and remove the ejs dependency.
Fixes https://github.com/Hexastack/Hexabot/issues/827
=> feat: use handlebars as template engine for mailing & remove ejs

api/src/chat/helpers/README.md, api/src/chat/helpers/envelope-builder.spec.ts, api/src/chat/helpers/envelope-builder.ts, api/src/chat/helpers/envelope-factory.spec.ts, api/src/chat/helpers/envelope-factory.ts, api/src/chat/schemas/types/message.ts, api/src/chat/services/block.service.spec.ts, api/src/chat/services/block.service.ts, api/src/plugins/plugins.module.ts, api/src/utils/helpers/safeRandom.spec.ts, api/src/utils/helpers/safeRandom.ts
This PR introduces two key components to streamline outgoing message envelope creation: the Envelope Builder and the Envelope Factory. Together, they offer a a developer friendly solution for constructing, localizing, and validating messages in various formats with minimal boilerplate.
- Envelope Builder: A Proxy-based builder utility that provides chainable setter methods to dynamically create envelope objects. It validates the final envelope using Zod schemas and supports dynamic array handling through methods like appendToQuickReplies.
- Envelope Factory: A higher-level abstraction that builds on the Envelope Builder. It integrates localization and templating using Handlebars and provides convenience methods for constructing different types of envelopes (text, quick replies, buttons, …
=> feat: envelope factory

api/src/chat/services/conversation.service.ts
=> fix: subscriber ctx var update logic

api/src/chat/controllers/message.controller.ts, api/src/chat/services/chat.service.ts
This PR includes adding missing event when emitting 'hook:chatbot:sent' event.
=> fix: hook chatbot sent event

api/src/cms/dto/contentType.dto.ts
=> Revert "fix: backward compatibility content type fields type"

api/src/cms/dto/contentType.dto.ts
=> Revert "Revert "fix: backward compatibility content type fields type""

api/src/chat/services/bot.service.ts
=> Revert "fix: resolve show more button issue"

api/src/chat/repositories/label.repository.ts, api/src/nlp/repositories/nlp-entity.repository.spec.ts, api/src/nlp/repositories/nlp-entity.repository.ts, api/src/nlp/repositories/nlp-value.repository.spec.ts, api/src/nlp/repositories/nlp-value.repository.ts, api/src/nlp/services/nlp.service.ts, api/types/event-emitter.d.ts
The main motivation of this PR is to use base-repository predefined hooks.
Fixes #1132
=> fix(api): resolve predefined create hooks bug

package-lock.json
The main motivation of this PR is to bump version 2.3.0
Fixes #1383
=> fix: bump version 2.3.0
