frontend/src/components/visual-editor/v2/Diagrams.tsx, package-lock.json
Fixed the bug which caused edit and remove buttons to remain active when category was switched, now the buttons are reset when the caategory is switched
Fixes #25 
Video of working proof:
https://www.loom.com/share/f3aff6514271415696145a0c47415206?sid=40577fab-3ba1-4734-bda9-3fae047b27a0
=> fix: [BUG] #25 -Edit & Remove Buttons stay active after category switch

frontend/src/components/visual-editor/v2/Diagrams.tsx
All the problems described in the issue are the result of an extra rerendering when a position of a block changes
The rerendering is automatically triggered when any data of any block changes, witch is what we want except for the position change because we then overwrite the library's default behavior.
Fixes #24
=> fix: remove extra rerendering when position changes

.github/workflows/merge.yml
This workflow automates the process of building and pushing Docker images for different parts of the project when changes are pushed to the main branch or triggered manually.
=> feat: add merge workflow

docker/docker-compose.dev.yml, docker/docker-compose.yml, frontend/Dockerfile, frontend/next.config.mjs, frontend/src/app-components/tables/columns/renderPicture.tsx, frontend/src/components/inbox/components/Chat.tsx, frontend/src/components/inbox/components/ChatActions.tsx, frontend/src/components/inbox/components/ConversationsList.tsx, frontend/src/components/inbox/helpers/mapMessages.tsx, frontend/src/components/nlp/components/NlpSample.tsx, frontend/src/components/users/index.tsx, frontend/src/hooks/useApiClient.tsx, frontend/src/hooks/useConfig.tsx, frontend/src/layout/Header.tsx, frontend/src/layout/VerticalMenu.tsx, frontend/src/pages/_app.tsx, frontend/src/pages/api/config.ts, frontend/src/pages/visual-editor.tsx, frontend/src/websocket/SocketIoClient.ts, frontend/src/websocket/socket-hooks.tsx
We need to push the docker images to dockerhub. To do so, config must be loaded on runtime.
=> Fix: load config on runtime

frontend/src/components/subscribers/index.tsx
this pr fixes the issue of small input search bar in subscribers section raised in issue number #16 raised by @marrouchi  
Fixes #16 
eariler the parent grid of the input was give a width of max-content due to which it was taking only the space required to show the content hence the search input was soo small.
In the fix i have changed the width from max-content to 50% hence increasing the width to 50% of the screen size.
=> Fixed issue #16: Subscribers search input is too small

frontend/src/i18n/en/translation.json
fix: Uppercase the first letter in NLP Value dialog form fields (#31)
Fixes #31
=> Update translation.json -- [ISSUE] - Uppercase the 1st letter in the NLP Value dialog form fields #31

frontend/src/i18n/en/translation.json, frontend/src/i18n/fr/translation.json
The **en/translation.json** and **fr/translation.json** files situated under the **/frontend/src/i18n/** directory contains duplicated label.type keys.
Fixes #63
=> fix: remove duplicated label.type translation keys

package-lock.json
In the package-lock.json file, packages section, is missing a license field.
The frontend, widget packages license and version fields are not updated.
Fixes #74
=> fix: update package-lock file version and license values

api/src/user/repositories/role.repository.spec.ts, api/src/user/repositories/role.repository.ts
Should perform cascade delete on permissions when a given role is deleted.
=> fix: delete role permissions

api/src/user/repositories/permission.repository.spec.ts
Add unit tests on deleteOne() in API user permission repository
Fixes https://github.com/Hexastack/Hexabot/issues/86
=> fix: added unit test case for permission deleteone api

.github/workflows/docker.yml, docker/docker-compose.dev.yml, frontend/Dockerfile, frontend/next.config.mjs
=> fix: add ui development target

frontend/src/components/visual-editor/v2/AdvancedLink/AdvancedLinkFactory.tsx
The main motivation is to avoid having an intersection between the curved link and the blocks, especially for blocks with a large height..
Before the update:
After the update:
Fixes #103
=> fix: enhance self linked block curve

api/src/user/schemas/user.schema.ts, frontend/src/app-components/tables/DataGrid.tsx, frontend/src/components/contents/index.tsx, frontend/src/components/context-vars/index.tsx, frontend/src/components/languages/index.tsx, frontend/src/components/users/index.tsx
This PR applies a consistent UI for toggle operations in the datagrid across all relevant pages (User, Content, Languages) in the Hexabot Chatbot builder. The update ensures that a Switch component is displayed in a dedicated column for all toggle operations, improving the user experience and maintaining UI consistency.
=> fix(frontend): align data grid toggle action

api/src/chat/services/block.service.ts, api/src/user/controllers/auth.controller.spec.ts, api/src/utils/helpers/safeRandom.ts, frontend/src/layout/Header.tsx, frontend/src/utils/generateId.ts, frontend/src/utils/safeRandom.ts
The motivation of this PR is to fix unsecured random functions uses cross the API and Frontend App's 
Fixes #105
=> fix: Insecure randomness

frontend/src/components/visual-editor/form/inputs/triggers/PatternInput.tsx, frontend/src/components/visual-editor/form/inputs/triggers/PatternsInput.tsx, frontend/src/i18n/en/translation.json, frontend/src/i18n/fr/translation.json
The main motivation is to fix the uncontrolled block form trigger empty messages.
Before the fix:
After the fix:
Fixes #122
=> fix(frontend): trigger empty messages input control

api/src/channel/channel.module.ts
Import http module in channels module so that channels could use the http service.
=> feat: import http module in channels module

cli/src/index.ts
For some reason, when using the cli to install an extension, the npm install doesn't update the package lock. 
"npm preinstall" which merges npm dependencies gets executed after the node modules are installed. This change makes sure preinstall is executed before the install.
=> fix: cli extension npm preinstall

frontend/src/components/visual-editor/BlockDialog.tsx
The main motivation of this change is to add the reset of the selected tabs tab when a user open to edit a block, 
which will make the mission easier to find the tab that he looking for.
Fixes #148
=> fix(frontend): add reset selected

api/src/setting/schemas/setting.schema.ts, frontend/src/components/settings/SettingInput.tsx, frontend/src/types/setting.types.ts
This PR fixes i18n issue with custom blocks settings form, labels do not show anymore. 
=> fix: i18n custom blocks settings

api/src/chat/controllers/category.contoller.spec.ts, api/src/chat/controllers/category.controller.ts, api/src/chat/repositories/category.repository.ts, frontend/src/components/categories/index.tsx, frontend/src/hooks/crud/useDeleteMany.tsx, frontend/src/services/api.class.ts
This PR includes the ability of performing a bulk delete operations on the flows:
Select multiple flows via check-boxes, and upon clicking "Delete," the selected categories should be removed from the list after confirmation.
Fixes # ([151](https://github.com/Hexastack/Hexabot/issues/151))
=> feat: add bulk delete functionality

frontend/src/app-components/attachment/AttachmentUploader.tsx, frontend/src/components/contents/ContentImportDialog.tsx, frontend/src/components/contents/index.tsx, frontend/src/hooks/useToast.ts, frontend/src/i18n/en/translation.json, frontend/src/i18n/fr/translation.json, frontend/src/services/api.class.ts
This PR is to include the endpoint for importing content CSV files. Now we can perform the import through a direct interaction within the UI side of the application.
```bash
1. Go to 'Manage Content > Content type'
2. Choose a content type and click  on 'content' in the operations column
3. Now you can import a new content using CSV files
```
=> fix: add content file upload input

frontend/src/app-components/inputs/AutoCompleteEntitySelect.tsx, frontend/src/app-components/inputs/AutoCompleteSelect.tsx, frontend/src/hooks/crud/useInfiniteFind.ts
While There is no strict limit on the maximum number of options you can provide to the Material-UI (MUI) Autocomplete control. However, performance may become an issue when dealing with a large number of options (e.g., thousands or more), as rendering and filtering so many options can cause lag in the UI. That's why we created the component "AutoCompleteEntitySelect" in the first place. If you have too many options, you can load the options asynchronously based on the user's input or scroll position, reducing the initial load.
This PR introduces the useInfiniteFind hook, which leverages react-query's useInfiniteQuery. It also updates AutoCompleteEntitySelect to use the new hook solving the racing condition between fetching VS rendering.
=> fix: autocomplete entity

frontend/src/app-components/attachment/AttachmentInput.tsx, frontend/src/app-components/attachment/AttachmentUploader.tsx, frontend/src/app-components/dialogs/DeleteDialog.tsx, frontend/src/components/contents/ContentImportDialog.tsx, frontend/src/components/contents/index.tsx, frontend/src/hooks/useDialog.tsx
This PR resolves the issue where the content list does not automatically refresh after importing a new CSV file. With this fix, the content will now update immediately following the CSV upload, eliminating the need for a manual page reload.
=> fix: content reload after import

api/src/chat/repositories/conversation.repository.ts, api/src/user/repositories/permission.repository.ts, api/src/user/repositories/role.repository.ts
The main motivation is to removing the duplicated populate methods.
Fixes #199
=> fix(api): remove duplicated populate methods

widget/.eslintrc.json, widget/src/components/ChatHeader.tsx, widget/src/components/ChatWindow.tsx, widget/src/components/ConnectionLost.tsx, widget/src/components/Launcher.tsx, widget/src/components/Message.tsx, widget/src/components/MessageStatus.tsx, widget/src/components/Messages.tsx, widget/src/components/UserInput.tsx, widget/src/components/Webview.tsx, widget/src/components/messages/CarouselMessage.tsx, widget/src/components/messages/ListMessage.tsx, widget/src/providers/ChatProvider.tsx, widget/src/providers/ColorProvider.tsx, widget/src/providers/SettingsProvider.tsx, widget/src/providers/SocketProvider.tsx, widget/src/providers/TranslationProvider.tsx
The motivation is to order well widget imports.
Fixes #238
=> fix(widget): eslint imports order

api/src/channel/channel.module.ts, api/src/channel/lib/Handler.ts, api/src/chat/controllers/block.controller.ts, api/src/chat/services/message.service.ts, api/src/i18n/services/i18n.service.ts, api/src/nlp/nlp.module.ts, api/src/plugins/base-block-plugin.ts, api/src/plugins/plugins.module.ts, api/src/plugins/plugins.service.spec.ts, api/src/plugins/types.ts, api/src/utils/helpers/misc.ts, api/src/utils/test/dummy/dummy.plugin.ts, frontend/src/components/settings/SettingInput.tsx, frontend/src/components/settings/index.tsx, frontend/src/components/visual-editor/CustomBlocks.tsx, frontend/src/components/visual-editor/form/OptionsForm.tsx, frontend/src/components/visual-editor/form/PluginMessageForm.tsx, frontend/src/services/entities.ts, frontend/src/types/block.types.ts
In this PR : 
- We introduce i18n for plugins 
- Enforce typing for plugin settings (arguments)
- Remove dummy plugin (keep it only for unit tests)
- https://github.com/Hexastack/hexabot-plugin-chatgpt/pull/2
- https://github.com/Hexastack/hexabot-plugin-gemini/pull/1
- Install chatgpt plugin as an example 
- Add a block, check the block message form : inputs should be translated (including helper text)
- Test the block
=> feat: add plugins settings i18n + typing

frontend/src/components/visual-editor/form/inputs/triggers/PatternInput.tsx
the main motivation of this update is to fix the input regex control in the block form triggers section
Fixes #167
=> fix(frontend): regex input control

api/src/setting/seeds/setting.seed.ts, api/src/setting/services/setting.service.ts
This PR fixes an issue with the settings cache : Once settings is seeded (insertMany), it doesn't invalidate the cache. This is causing an issue on app init (api sometimes fails to start and sometimes add duplicate settingss)
=> fix: clear setting cache once seeded

frontend/public/locales/en/translation.json, frontend/public/locales/fr/translation.json, frontend/src/components/visual-editor/form/inputs/triggers/PatternInput.tsx
The main motivation of this PR is to fix a bug existing actually in the Visual Editor. 
The block pattern field is displayed incorrectly in the UI.
Fixes #270
Cases fully support by this proposed change :
- Invalid regex case
- Empty regex case
- Edge case pattern that can bypass the check logic
=> fix(frontend): visual editor pattern UI representation

package.json
The motivation of this update is to remove the cli from the package.json file
Fixes #282
=> fix: unused old cli from package.json file

nlu/Dockerfile
The main motivation of this PR is to fix NLU dockerfile missing expose port.
=> fix: missing nlu dockerfile expose port

frontend/public/locales/en/chatbot_settings.json, frontend/public/locales/en/translation.json, frontend/public/locales/fr/chatbot_settings.json, frontend/public/locales/fr/translation.json, frontend/src/components/settings/SettingInput.tsx
The main motivation of this PR is to fix a bug existing in the Settings page > chatbot.
The issue is that after adding a fallback plugin we are unable to remove it.
Fixes #255
=> fix(frontend): removing default plugin issue

api/src/chat/repositories/block.repository.ts, api/src/chat/services/block.service.ts, api/src/chat/validation-rules/is-message.ts
The main motivation of this PR is to support block.message.payload.attachment_id to fix the attachment block edit form submit issue.
Fixes #276 
<video src="https://github.com/user-attachments/assets/903c5819-39ef-4320-8b84-28f3c74c4b95" />
=> fix(api): schema support attachment_id nullable value

api/src/utils/types/filter.types.ts
The main motivation of this PR is to remove nested types having function type from the nested queries autocomplete.
Fixes #314
=> fix(api): exclude functions as nested types

widget/src/components/UserInput.tsx
The main motivation of this update is to fix the issue happening the text field of the widget
Fixes #242
<video src="https://github.com/user-attachments/assets/67664797-43e5-4fb1-881b-8d65fd83fbba" />
=> fix: restrict paste content to have text format+don't lose old text

frontend/src/components/context-vars/ContextVarDialog.tsx
The main motivation of this PR is to fix an issue situated in the ContextVar edit dialog component.
Fixes #338
<video src="https://github.com/user-attachments/assets/8d0f70eb-5db2-44dd-a9ef-38068cad5187" />
=> fix(frontend): contextVar edit dialog states

api/src/channel/lib/__test__/common.mock.ts, api/src/chat/schemas/types/message.ts, api/src/chat/services/block.service.spec.ts, api/src/cms/schemas/content.schema.ts, api/src/cms/services/content.service.spec.ts, api/src/cms/services/content.service.ts, api/src/extensions/channels/web/base-web-channel.ts
This PR fixes things about lists and carousel. We have now : 
1. Content (that is the object as stored in DB - with dynamicFields)
2. ContentElement which is a flattened form of the content. It would be used in list / carousel ("elements" attribute)
This should solve the confusion around both, both in channel and plugins.
=> fix: content vs element

api/src/chat/controllers/block.controller.spec.ts, api/src/chat/controllers/block.controller.ts, api/src/chat/controllers/category.controller.ts, api/src/chat/controllers/context-var.controller.ts, api/src/chat/controllers/label.controller.ts, api/src/chat/controllers/message.controller.ts, api/src/chat/controllers/subscriber.controller.ts, api/src/cms/controllers/content-type.controller.ts, api/src/cms/controllers/content.controller.ts, api/src/cms/controllers/menu.controller.ts, api/src/i18n/controllers/language.controller.ts, api/src/i18n/controllers/translation.controller.ts, api/src/nlp/controllers/nlp-entity.controller.ts, api/src/nlp/controllers/nlp-sample.controller.ts, api/src/nlp/controllers/nlp-value.controller.ts, api/src/user/controllers/role.controller.ts, api/src/user/controllers/user.controller.ts, api/src/utils/pagination/pagination-query.dto.ts, api/src/utils/pagination/pagination-query.pipe.ts
This PR addresses an issue where the hasCount parameter in the API does not properly disable the query limit for the Visual Editor. Despite passing hasCount as false, the API still applies a limit to the find query, causing unexpected behavior when managing a large number of flows.
A temporary fix was previously applied for the Visual Editor case in PR #357. This update ensures the hasCount parameter functions as intended across all relevant components, removing the reliance on temporary solutions.
ISSUE #358 
=> fix: pagination

api/src/i18n/services/translation.service.ts
Fixes an API crash caused by accessing properties on an undefined plugin object when processing translations.
- Added optional chaining to safely access plugin and `plugin.settings` properties.
=> fix: add null checks for plugin and settings to prevent TypeError

nlu/models/intent_classifier.py, nlu/models/slot_filler.py
In this PR we adapt the slot filler model to load the bert model names from the env var by language. 
=> fix: add missing bert load from env var

api/src/app.module.ts, api/src/attachment/schemas/attachment.schema.ts, api/src/cms/schemas/content.schema.ts, api/src/config/index.ts, api/src/config/types.ts, api/src/extensions/channels/console/settings.ts, api/src/websocket/pipes/io-message.pipe.ts, api/src/websocket/utils/socket-request.ts
The main motivation of this PR is to refactor the current logic to centralize apiUrl and appUrl environment variables.
Fixes #390
=> Update config to use env var when defining the apiUrl and appUrl

frontend/src/components/visual-editor/v2/CustomDiagramNodes/NodeWidget.tsx, frontend/src/utils/text.ts
This PR addresses the issue where long messages in the Visual Editor were not being truncated :
before : 
after : 
Fixes #345
=> fix: truncate long messages in visual editor

api/src/analytics/schemas/bot-stats.schema.ts, api/src/nlp/schemas/nlp-sample-entity.schema.ts
The main motivation of this PR is to attach botStats and nlpSampleEnitity models to the lifecyclehook
Fixes #401
=> fix: attach botStats and nlpSampleEnitity to the lifecyclehook

widget/src/components/messages/FileMessage.tsx, widget/src/components/messages/GeolocationMessage.tsx, widget/src/components/messages/ListMessage.tsx, widget/src/components/messages/TextMessage.tsx
This PR refactors the widget application to replace hard-coded 'received' with Direction enum, improving maintainability and reducing the risk of errors. 
Fixes #411
=> refactor: hard coded direction values with enum

api/src/chat/services/chat.service.ts, widget/src/providers/ChatProvider.tsx
The main motivation of this PR is to make synchronized the sent message for the same account.
Fixes #392
<video src="https://github.com/user-attachments/assets/211241a1-f7b5-4156-9638-1860f4b17cb8" />
=> fix: synchronized sended messages for the same accounts

api/types/event-emitter.d.ts
The main motivation of this PR is to fix an typescript issue with updating eventEmitter file to exclude normalized event names from customized events.
Fixes #408
=> fix: update eventEmitter to exclude normalized event names from customized events

api/src/attachment/controllers/attachment.controller.ts, api/src/chat/controllers/message.controller.ts, api/src/chat/repositories/message.repository.ts, api/src/chat/repositories/subscriber.repository.ts, api/src/chat/services/message.service.ts, api/src/cms/controllers/content.controller.ts, api/src/cms/services/content.service.ts, api/src/utils/generics/base-repository.ts, api/src/utils/generics/base-service.ts
The motivation of this PR is to add retro compatibility for find and findAndPopulate methods.
reference: https://www.mongodb.com/docs/manual/reference/method/cursor.limit/
Fixes #418
=> fix: add retro compatibility for find and findAndPopulate methods

frontend/src/components/visual-editor/form/inputs/message/ButtonsInput.tsx
The motivation of this PR is to make equal the validation of the max number of buttons between API and the UI.
Fixes #321
=> fix: sync UI button max number validation with the API validation

api/src/setting/repositories/setting.repository.ts, api/src/utils/generics/base-repository.spec.ts, api/src/utils/generics/base-repository.ts, api/types/event-emitter.d.ts, frontend/src/components/settings/SettingInput.tsx, frontend/src/components/settings/index.tsx
This PR fixes the issue when updating a setting field that should be saved as Number and saved as String in MongoDB because mongoose middleware/hooks does not run by default on findOneAndUpdate
Fixes #427
=> Fix : Number settings gets saved as strings in MongoDB

frontend/src/components/visual-editor/form/ListMessageForm.tsx
This PR addresses the issue in List Block contentTypes of type text-area aren't displayed as an option 
Fixes #452
=> fix: display contentType text-area fields in list block

api/src/utils/pipes/search-filter.pipe.spec.ts, api/src/utils/pipes/search-filter.pipe.ts, api/src/utils/types/filter.types.ts
In this PR we: 
- Add support to array values in search filters
- Rename attributes (operator, context, ..) to avoid possible conflicts with entities attributes
- Added unit tests
=> feat: add support for arrays in search filter

.github/workflows/pull_request.yml, .github/workflows/release.yml, .husky/pre-commit, api/.dockerignore, api/.eslintrc-staged.js, api/.eslintrc.js, api/package-lock.json, api/package.json, frontend/.dockerignore, frontend/.eslintrc-staged.js, frontend/.eslintrc.js, frontend/package.json, widget/.dockerignore, widget/.eslintrc-staged.json, widget/.eslintrc.json, widget/package.json
The motivation of this PR is to fix Eslint Header license to be updated (year) only if it's modified.
Fixes #498
=> fix: restrict eslint license header year update to staged files

api/src/helper/helper.service.ts, api/src/plugins/plugins.service.ts
This PR fixes duplicate name issue with Plugins & ensure the code compatible with strict null check
=> Fix: plugins strict null check

api/tsconfig.json
The main motivation of this PR is to disable strict Property Initialization
Fixes #525
=> fix: disabled tsconfig strict Property Initialization

api/src/analytics/validation-rules/is-less-than-date.ts, api/src/utils/validation-rules/is-object-id.ts
This PR fixes Decorator  IsLessThanDate and IsObjectId to comply with strict null check
- [x Bug fix (non-breaking change which fixes an issue)
=> fix: utilities decorators IsLessThanDate, IsObjectId

api/src/utils/pagination/pagination-query.pipe.ts
The motivation of this PR is to resolve pagination-querypipe null checks issues 
Fixes #527
=> [MERGE ORDER 1] fix: resolve pagination-querypipe null checks issues

api/src/user/controllers/auth.controller.spec.ts, api/src/user/controllers/auth.controller.ts, api/src/user/controllers/model.controller.spec.ts, api/src/user/controllers/user.controller.spec.ts, api/src/user/controllers/user.controller.ts, api/src/user/dto/user.dto.ts, api/src/user/guards/ability.guard.ts, api/src/user/passport/session.serializer.ts, api/src/user/repositories/invitation.repository.spec.ts, api/src/user/repositories/model.repository.spec.ts, api/src/user/repositories/user.repository.spec.ts, api/src/user/schemas/user.schema.ts, api/src/user/seeds/user.seed-model.ts, api/src/user/services/auth.service.spec.ts, api/src/user/services/invitation.service.spec.ts, api/src/user/services/invitation.service.ts, api/src/user/services/model.service.spec.ts, api/src/user/services/passwordReset.service.spec.ts, api/src/user/services/passwordReset.service.ts, api/src/user/services/user.service.spec.ts, api/src/user/services/validate-account.service.ts, api/src/utils/test/fixtures/user.ts, api/src/utils/types/filter.types.ts
The motivation of this PR is to resolve User Module null checks issues
Fixes #538
=> fix: User module issues

api/src/helper/lib/__test__/base-nlp-helper.spec.ts, api/src/helper/lib/__test__/settings.ts, api/src/helper/lib/base-nlp-helper.ts
The Following PR fixes the dataset export feature issue when no helper is specified by adding a default implementation
Fixes # (issue) 
https://github.com/Hexastack/Hexabot/issues/463
=> fix: add default format implementation

api/src/attachment/controllers/attachment.controller.spec.ts, api/src/attachment/controllers/attachment.controller.ts, api/src/attachment/services/attachment.service.ts, api/src/extensions/helpers/llm-nlu/index.helper.ts, api/src/migration/migration.service.spec.ts, api/src/migration/migration.service.ts, api/src/migration/migrations/1735836154221-v-2-2-0.migration.ts, api/src/migration/types.ts, api/src/nlp/controllers/nlp-entity.controller.spec.ts, api/src/nlp/controllers/nlp-value.controller.spec.ts, api/src/nlp/controllers/nlp-value.controller.ts, api/src/nlp/dto/nlp-value.dto.ts, api/src/nlp/repositories/nlp-value.repository.spec.ts, api/src/nlp/seeds/nlp-value.seed.ts, api/src/nlp/services/nlp-value.service.spec.ts, api/src/nlp/services/nlp-value.service.ts, api/src/utils/generics/base-repository.ts, api/src/utils/generics/base-service.ts, api/src/utils/helpers/fs.ts, api/src/utils/pipes/object-id.pipe.ts, api/src/utils/test/fixtures/conversation.ts, api/src/utils/test/fixtures/nlpvalue.ts, api/tsconfig.json
The main motivation is to implement strict null checks
Fixes #562
=> feat: implement strict null checks

frontend/src/components/visual-editor/form/ListMessageForm.tsx
This PR main motivation is to resolve the missing default values for the list block edit modal.
Fixes #575
=> fix(frontend): resolve block list edit form bug

frontend/src/contexts/auth.context.tsx, frontend/src/hooks/entities/auth-hooks.ts, frontend/src/hooks/useApiClient.ts
This PR addresses the issue when users logs out, the dashboard displays for a second then page refreshes and logs out the user
Fixes #594
=> fix: logout

frontend/Dockerfile
This PR addresses the issue when running in dev/prod mode the frontend gets error trying to patch package.lockfile.json
Fixes #607
=> fix: patch-lock-file error in dev & prod mode

api/src/chat/controllers/block.controller.ts, api/src/i18n/services/translation.service.spec.ts, api/src/i18n/services/translation.service.ts, api/src/plugins/base-block-plugin.ts
The following PR updates block settings visibility to private in order to avoid confusion between default block settings and block args.
Fixes # ([598](https://github.com/Hexastack/Hexabot/issues/598))
=> feat: update block plugin settings visibility

api/src/chat/services/chat.service.ts
This PR addresses the issue of duplicate event emitted `new_users` and removes it  (event is already emitted in the subscriber postCreate() hook)
=> fix: remove duplicate emitted event 'new_users'

frontend/Dockerfile
This PR fixes issues related to docker not caching frontend  steps
Fixes #606
=> fix: optimize docker frontend cache

frontend/src/app-components/inputs/PasswordInput.tsx
React's focus behavior can be affected when a component re-renders due to state changes. In this case, updating the local password state caused the PasswordInput component to re-render unnecessarily. This re-render could interfere with the input field's focus.
Fixes https://github.com/Hexastack/Hexabot/issues/593
=> fix: remove unnecessary state change

widget/src/components/UserSubscription.tsx, widget/src/providers/ChatProvider.tsx, widget/src/utils/SocketIoClient.ts
This PR fixes an issue where a user loses their subscription (e.g., joining the correct IO room) after losing internet connectivity and reconnecting. The added functionality ensures that users are automatically re-subscribed upon reconnection to maintain seamless functionality.
- Use the chat widget
- Restart the API 
- Use the chat again, it should respond to messages 
=> fix: re-subscribe on ws reconnect

api/src/helper/lib/base-nlp-helper.ts
Make sure that the return type of the format() method in any NLU helper is generic.
=> fix: nlu format return

api/src/chat/repositories/subscriber.repository.ts
This change ensures that the `findOneByForeignId()` method behaves consistently by returning `Subscriber | null`, just like the `findOne()` method. Adding a `null` check increases reliability and prevents potential errors when the method is called with a foreign ID that doesn't exist. This update improves the code's robustness and aligns with best practices.
Fixes #614
=> fix: update return type of findOneByForeignId to include null

frontend/src/app-components/inputs/FileInput.tsx, frontend/src/utils/attachment.ts, widget/src/components/buttons/FileButton.tsx, widget/src/utils/attachment.ts
This PR:
-  Adds new mimes types
- Fix issue in the widget where we are not providing which mime types user can send
- Fix issue in the user avatar where the input doesn't have accept values mime types thus able to pick a PDF as avatar
we should check if some of mime types i' have added aren't necessary
Fixes #650
=> Fix: update accepted attachments mime types

widget/src/ChatWidget.tsx
This PR fixes a bug in widget project where it doesn't display the web-widget
Fixes #672
=> fix: broadcast channel provider missing for widget

frontend/src/app-components/dialogs/FormDialog.tsx, frontend/src/components/nlp/components/NlpSample.tsx, frontend/src/components/nlp/components/NlpSampleForm.tsx, frontend/src/components/nlp/components/NlpSampleFormDialog.tsx, frontend/src/contexts/dialogs.context.tsx, frontend/src/types/common/dialogs.types.ts
The main motivation is to refactor the NlpSamples code base to use useDialogs hook instead of using useDialog hook.
Fixes #695
=> refactor(frontend): update nlpSample dialogs

frontend/src/components/inbox/components/Chat.tsx, frontend/src/components/inbox/components/GeolocationMessage.tsx, frontend/src/components/inbox/helpers/mapMessages.tsx, frontend/src/types/message.types.ts
This PR fixes a bug where when user sends their `location` it displays empty message in the `inbox`
Fixes #352 
=> fix: location does not display in inbox conversation

frontend/src/app-components/widget/ChatWidget.tsx, frontend/src/hooks/useAuth.ts
This PR removes the import & utilization of app router
=> fix: use pages router instead of app router

api/src/chat/schemas/types/message.ts, api/src/chat/validation-rules/is-message.ts
This PR refactors `zod` validation for `BlockMessage` & removes old unused validation
=> feat: refactor zod validation

api/src/chat/schemas/block.schema.ts, api/src/utils/helpers/zod-validation.ts
This PR refactors mongoose validation to work with higher order function using zod schema
=> refactor: mongoose validation

frontend/src/components/visual-editor/v2/Diagrams.tsx
The `visual editor` captures all `drag and drop events` within it, and handles only those of a `block`.
But when checking if an event is related to a block, `JSON parsing` of an empty string may happen, which causes an error.
This `PR` fixes this issue.
=> fix: non-block drop in visual editor

api/src/setting/index.d.ts
The main motivation is to make setting with SettingType.select type inferring the options types.
Fixes #752
=> fix: make SettingType.select inferring options as type

frontend/src/components/Menu/MenuForm.tsx, frontend/src/components/categories/CategoryForm.tsx, frontend/src/components/content-types/ContentTypeForm.tsx, frontend/src/components/contents/ContentForm.tsx, frontend/src/components/contents/ContentImportForm.tsx, frontend/src/components/context-vars/ContextVarForm.tsx, frontend/src/components/labels/LabelForm.tsx, frontend/src/components/languages/LanguageForm.tsx, frontend/src/components/nlp/components/NlpEntityForm.tsx, frontend/src/components/nlp/components/NlpValueForm.tsx, frontend/src/components/profile/profile.tsx, frontend/src/components/roles/RoleForm.tsx, frontend/src/components/subscribers/SubscriberForm.tsx, frontend/src/components/users/EditUserForm.tsx, frontend/src/components/users/InviteUserForm.tsx, frontend/src/components/visual-editor/BlockEditForm.tsx, frontend/src/components/visual-editor/BlockMoveForm.tsx, frontend/src/components/visual-editor/form/MessageForm.tsx, frontend/src/components/visual-editor/form/OptionsForm.tsx, frontend/src/components/visual-editor/form/TriggersForm.tsx
The main motivation of this PR is to introduce the using of the dialogs short imports.
For more details you can see the dedicated issue #762
Fixes #762
=> fix(frontend): use short dialogs imports

frontend/src/app-components/inputs/Selectable.tsx, frontend/src/components/nlp/components/NlpTrainForm.tsx
This PR introduces a loading state to the `Selectable` component to improve the user experience while fetching NLP predictions. The `CircularProgress` spinner is displayed during API requests to indicate loading status.  
Fixes issue: #638 
- **Added a loading state** in `Selectable.tsx` using `useQuery` with `react-query`.  
- **Passed `isLoading` prop** to the `Selectable` component for better state management.  
- **Displayed a `CircularProgress` spinner** inside `Selectable` when `loading` is `true`.  
- **Ensured proper styling** of the spinner to align correctly with the input field.
=> Added a loading spinner in NLU prediction 

api/src/chat/repositories/category.repository.ts
Error message of bulk Flow (categories) delete are now clear.
Associated to [Issue #740](https://github.com/Hexastack/Hexabot/issues/740)
=> fix: appropriate toast message on category bulk delete

frontend/public/locales/en/translation.json, frontend/public/locales/fr/translation.json, frontend/src/components/visual-editor/v2/Diagrams.tsx
This PR introduces the ability to duplicate a `Block` along with its current configuration.
=> feat: duplicate a block 2

api/src/chat/schemas/types/button.ts, api/src/chat/schemas/types/message.ts, api/src/chat/schemas/types/pattern.ts, api/src/chat/schemas/types/quick-reply.ts, api/src/chat/services/block.service.spec.ts, api/src/extensions/channels/web/base-web-channel.ts, api/src/extensions/channels/web/wrapper.ts, api/src/utils/test/mocks/block.ts
We refactored PayloadType in button file it was causing issues with zod (recursive imports between message.ts & quick reply)
Should be merged along with these PRS :orange_circle: :
- https://github.com/Hexastack/hexabot-channel-whatsapp/pull/13
- https://github.com/Hexastack/hexabot-channel-discord/pull/10
- https://github.com/Hexastack/hexabot-channel-messenger/pull/18
- https://github.com/Hexastack/hexabot-channel-slack/pull/16
=> Feat: zod validation message refactor payload type

frontend/src/components/nlp/components/NlpSample.tsx
This PR fixes a UI alignment issue on the NLU page where the **Delete** button was misaligned. The issue was caused by an extra `Grid` wrapper that was affecting button alignment. Removing it resolved the issue while keeping the layout consistent.  
**Fixes:** #773
=> refactor: fixed the alignment of the button

frontend/src/components/inbox/components/AttachmentViewerForm.tsx, frontend/src/components/inbox/components/Carousel.tsx
Carousel Buttons: Improved visibility of carousel navigation buttons when displayed over dark or black images by adding a contrasting background and hover effect.
Inbox Attachments: Resolved image cropping issue when opening attachments from the inbox by adjusting the container styling and ensuring proper aspect ratio.
Fixes #584
=> Fixed carousel buttons not visible on dark image (black) and opening attachment from the inbox croping the image

api/package-lock.json, api/package.json, api/src/chat/schemas/types/context.ts, api/src/chat/services/block.service.spec.ts, api/src/chat/services/block.service.ts, frontend/src/components/visual-editor/form/inputs/ReplacementTokens.tsx
This PR introduces Handlebars template rendering for block messages within Hexabot. The goal is to allow dynamic token replacements in messages, so that context-dependent values can be injected and displayed at runtime. By integrating Handlebars, we gain a more flexible way to insert user-specific or environment-specific variables into our messages.
Fixes #https://github.com/Hexastack/Hexabot/issues/819
Fixes https://github.com/Hexastack/Hexabot/issues/817
=> feat: add handlebars template for text

api/src/chat/services/chat.service.ts
The main goal of this PR is to synchronize sent messages cross opened websocket connections of the same account.
Fixes #810
=> fix: synchronized sent messages cross account tabs

api/src/utils/generics/base-controller.ts, api/src/utils/generics/base-repository.ts, api/src/utils/generics/base-service.ts
The main motivation is to move canPopulate method to the base-repository and to make the method available from the service level.
Fixes #845
=> fix: move canPopulate method to the base-repository

api/src/nlp/controllers/nlp-sample.controller.spec.ts, api/src/nlp/controllers/nlp-value.controller.spec.ts, api/src/nlp/controllers/nlp-value.controller.ts, api/src/nlp/dto/nlp-value.dto.ts, api/src/nlp/schemas/nlp-value.schema.ts, api/src/utils/test/fixtures/nlpvalue.ts, frontend/src/components/nlp/components/NlpValue.tsx, frontend/src/components/nlp/components/NlpValueForm.tsx, frontend/src/types/nlp-value.types.ts
The following PR adds a description attribute for each NLP value. This will allow us to attach additional explanatory information or context to the NLP value in the system. 
//@TODO : add support for search functionality on NLP values' descriptions
Fixes # ([387](https://github.com/Hexastack/Hexabot/issues/837))
[Screencast from 2025-03-21 12-13-04.webm](https://github.com/user-attachments/assets/c86c7371-fb6e-4299-8001-0307655d876d)
=> feat: add description attribute for nlu values

api/src/nlp/controllers/nlp-sample.controller.ts
This PR fixes the issue where nlp-same pagination doesn't work due to missing value allowedFields in `SearchFilterPipe`
Fixes [#420](https://github.com/Hexastack/Hexabot/issues/420)
=> fix: nlp-sample pagination

api/src/chat/controllers/block.controller.spec.ts, api/src/chat/schemas/types/button.ts
This PR fixes the issue where the PayloadType enum missing `menu` value
Fixes #716
=> fix: missing value in PayloadType enum

api/src/chat/services/bot.service.ts
addresses an issue in the Hexabot project where the bot would hang if a conversation block had no matching outcomes. The proposed change ensures that the conversation ends gracefully in such scenarios, preventing the bot from becoming unresponsive.
Fixes #878
=> fix: end conversation when a block have no matching outcomes

CONTRIBUTING.md
The main motivation of this PR is to updating the contributing.md file in goal to include the end-to-end contribution flow is designed to make teamwork smoother and more efficient. It starts with creating a branch for your changes, followed by coding and testing your updates. Once ready, you submit a Pull Request (PR) for review. Team members can then review, suggest improvements, and approve the changes. After approval, the updates are merged into the main project. This clear, step-by-step process ensures everyone is on the same page, reduces errors, and helps the team achieve its goals faster :rocket: 
Fixes #749
=> fix: write an end-to-end contribution flow

frontend/src/components/visual-editor/CustomBlocks.tsx
This PR ensures sorting (based on name) custom plugins before rendering them to ensure display order consistency 
Fixes #867
=> fix: custom plugins displayed unsorted

api/src/chat/services/bot.service.ts
addresses the removal of an unused parameter in the hook-conversation-end event emission. This change simplifies the event emission process and enhances code clarity.
Fixes #881
=> fix: remove unused parameter when emitting hook-conversation-end event

frontend/src/contexts/auth.context.tsx, frontend/src/utils/URL.ts
This PR ensures that query parameters are retained when a user logs out. After logging back in, the user is redirected to their previous pathname with the original query parameters preserved
Fixes #798
=> feat: support redirection with query params

api/src/extensions/helpers/llm-nlu/index.helper.ts, api/src/nlp/services/nlp-entity.service.ts
Use cache to retrieve entities for deterministic matching.
=> feat: use cache

frontend/src/hooks/crud/useInfiniteFind.ts, frontend/src/hooks/crud/useNormalizedInfiniteQuery.ts, frontend/src/types/base.types.ts
The params in useInfiniteFind hook currently uses any type. This is unsafe and can cause bugs.
Add proper TypeScript types to the params option.
- Catches errors early 🚨
- Makes the code easier to understand 📖
- Better autocomplete in IDEs 💡
Fixes #1247
=> fix(frontend): update useInfiniteFind typing

api/src/user/seeds/model.seed-model.ts, api/src/user/types/model.type.ts, frontend/public/locales/en/translation.json, frontend/public/locales/fr/translation.json, frontend/src/app-components/inputs/AutoCompleteEntitySelect.tsx, frontend/src/app-components/inputs/AutoCompleteSelect.tsx, frontend/src/components/labels/LabelForm.tsx, frontend/src/components/labels/index.tsx, frontend/src/services/api.class.ts, frontend/src/services/entities.ts, frontend/src/services/types.ts, frontend/src/types/base.types.ts, frontend/src/types/label-group.types.ts, frontend/src/types/label.types.ts
The main motivation is to add the UI side of the label Mutex feature.
- Added **mutex group** selection in the UI  
- **Delete confirmation** dialog for safety  
- **updates** when changes are made  
✅ Prevents accidental deletions (with confirmation)  
🤖 Smarter auto-selection saves clicks  
🔄 Updates UI instantly after changes  
<video src="https://github.com/user-attachments/assets/a5d0b27a-cffc-4631-acf9-aa6cd01a479f"></video> 
Fixes #1283
=> feat: Add label Mutex Group UI (CRUD)
